import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    actionButtons: {
      height: 56,
      backgroundColor: 'transparent',
      flexDirection: 'row',
      alignSelf: 'flex-end',
    },
    camera: {
        flex: 1,
        justifyContent: 'space-between',
    },
    container: {
        flex: 1,
        paddingTop: 10,
        backgroundColor: '#000',
      },
      selectedButton: {
        flex: 0.3,
        height: 40,
        marginHorizontal: 2,
        marginBottom: 10,
        marginTop: 10,
        borderRadius: 8,
        borderColor: 'red',
        borderWidth: 1,
        padding: 5,
        alignItems: 'center',
        justifyContent: 'center',
      },
      autoFocusBox: {
        position: 'absolute',
        height: 64,
        width: 64,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'white',
        opacity: 0.4,
      },
      flipText: {
        color: 'white',
        fontSize: 15,
      },
      zoomText: {
        position: 'absolute',
        bottom: 70,
        zIndex: 2,
        left: 2,
      },
      picButton: {
        backgroundColor: 'darkseagreen',
        flex: 0.3,
        height: 40,
        marginHorizontal: 2,
        marginBottom: 10,
        marginTop: 10,
        borderRadius: 8,
        borderColor: 'darkseagreen',
        borderWidth: 1,
        padding: 5,
        alignItems: 'center',
        justifyContent: 'center',
      },
      selectedPicButton: {
        backgroundColor: 'red',
      },
      facesContainer: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        left: 0,
        top: 0,
      },
      face: {
        padding: 10,
        borderWidth: 2,
        borderRadius: 2,
        position: 'absolute',
        borderColor: '#FFD700',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      landmark: {
        position: 'absolute',
        backgroundColor: 'red',
      },
      faceText: {
        color: '#FFD700',
        fontWeight: 'bold',
        textAlign: 'center',
        margin: 10,
        backgroundColor: 'transparent',
      },
      text: {
        padding: 10,
        borderWidth: 2,
        borderRadius: 2,
        position: 'absolute',
        borderColor: '#F00',
        justifyContent: 'center',
      },
      textBlock: {
        color: '#F00',
        position: 'absolute',
        textAlign: 'center',
        backgroundColor: 'transparent',
      },
});

export default styles;
